---
- name: Render Configs
  ansible.builtin.template:
    src: "{{ item.value.template }}"
    dest: "{{ item.value.destination }}"
    mode: u=rw,g=r,o=r
  loop: "{{ lookup( 'dict', base_managed_configs) }}"
