---
# tasks file for base
#
- name: Install base RPMs
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  become: true
  register: dnf_result
  loop:
    - "{{ base_rpms }}"
    - "{{ base_rpms_extra }}"

- name: Render configs
  include_tasks: configs.yml

- name: Setup theme stuff
  include_tasks: themes.yml
