---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora36
    image: quay.io/fedora/fedora:36
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
